# Funding options for this project

github: []  # Możesz dodać tutaj swojego GitHub Sponsors username, jeśli używasz
custom: 
  - https://buycoffee.to/art
  - https://subscribepage.io/art
  - https://www.linkedin.com/comm/mynetwork/discovery-see-all?usecase=PEOPLE_FOLLOWS&followMember=artur-markiewicz
